### ISSUE TITLE
zeek_agent_hosts.zeek at lines (168-176) has duplicate declaration of the hook

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/zeek-agent-framework#8]
https://github.com/zeek/zeek-agent-framework/blob/master/zeek-agent/framework/zeek_agent_hosts.zeek
at lines (168-176) has duplication of the hook.

I confirmed by experimentation, that zeek just absorbs this silently, but should there be a check, syntax-error-wise ?
```
module MyHTTPAgent;

export {
	## Hook that can be called by others to indicate that an IP address was added to a host
	global add_host_addr: hook(host_id: string, ip: addr);
}

function send_joins_new_address(host_id: string, ip: addr)
	{
	local new_groups: vector of string;
        }	

event MyHTTP::request_line(c: connection, method: string, uri: string, version: string)
	{
	print fmt("Zeek saw from %s: %s %s %s", c$id$orig_h, method, uri, version);
	}

hook MyHTTPAgent::add_host_addr(host_id: string, ip: addr)
	{
	send_joins_new_address(host_id, ip);
	}

hook MyHTTPAgent::add_host_addr(host_id: string, ip: addr)
	{
	#TODO
	}
outputs:

~/Documents/work/projects/zeek/build/src/zeek -Cr MyHTTP-request-line.pcap MyHTTP.spicy MyHTTP.evt MyHTTP_double_declaring_hook.zeek
GET, /index.html, 1.0
```
Zeek saw from 127.0.0.1: GET /index.html 1.0
(This was earlier posted as zeek-agent Issue #64)

**Comment by rsmmr** [comment]
Hooks can be implemented multiple times. That's by design, they are like events in that regard, with all implementations executing (unless an earlier one explicitly aborts).

In this specific case, not sure why we'd need two here. Whatever the TODO is, should be able to go into the 1st implementation of the hook as well. But that's a semantic questions, from a language perspective this is fine.
